concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' &&
    format('ci-pull-{0}', github.event.pull_request.number) || format('ci-main-{0}',
    github.sha) }}
env:
  MAVEN_CUSTOM_OPTS: -Xmx4g -XX:+ExitOnOutOfMemoryError
jobs:
  Build_Unit_Test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha
          || github.sha }}
        submodules: 'true'
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.5.0
    - continue-on-error: true
      id: cache-maven
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ github.workflow }}-${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ github.workflow }}-${{ runner.os }}-maven-2-

          '
    - continue-on-error: true
      if: steps.cache-maven.outputs.cache-hit != 'true'
      name: Populate maven cache
      run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
    - continue-on-error: true
      name: Maven Build
      run: 'export MAVEN_OPTS="${MAVEN_CUSTOM_OPTS}"

        ./mvnw -T 1C clean package install -DskipTests -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true

        '
    - continue-on-error: true
      name: Unit Test
      run: 'export MAVEN_OPTS="${MAVEN_CUSTOM_OPTS}"

        sudo sed -i ''s#.*#Asia/Shanghai#g'' /etc/timezone

        ./mvnw test -B -pl ''!polardbx-calcite,!polardbx-rule,!polardbx-rpc,!polardbx-test''
        -Dmaven.test.failure.ignore=true

        '
    - continue-on-error: true
      name: Analyze Unit Test Result
      uses: scacap/action-surefire-report@v1
      with:
        check_name: Unit Test Result
        fail_on_test_failures: true
        report_paths: polardbx-*/target/surefire-reports/TEST-*.xml
name: Build_Unit_Test
on:
  repository_dispatch:
    types: trigger-ga___build_and_unit_test.yaml
permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write
