concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' &&
    format('ci-pull-{0}', github.event.pull_request.number) || format('ci-main-{0}',
    github.sha) }}
env:
  CODE_REF: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref
    || github.ref }}
  COMMIT_ID: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha
    || github.sha }}
  GIT_URL: https://github.com/${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name
    || github.repository }}
jobs:
  DDL_TEST:
    env:
      TEST_UID: ${{ github.run_id }}-${{ github.run_attempt }}-ddl
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name,
      'ready for test')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Print ENV
      run: 'echo "test_uid: ${TEST_UID}"

        echo "git_url: ${GIT_URL}"

        echo "commit_id: ${COMMIT_ID}"

        echo "code_ref: ${CODE_REF}"

        '
    - continue-on-error: true
      id: ddl_deploy
      name: Deploy PolarDB-X Cluster
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 100m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./k8s_deploy.sh -u ${TEST_UID} --repository ${GIT_URL} --ref ${CODE_REF}
          --commit ${COMMIT_ID}

          '
        username: ${{ secrets.ECS_USERNAME }}
    - continue-on-error: true
      name: Load Init Data
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 60m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./load_data_by_pod.sh -u ${TEST_UID} --only_create_database

          '
        username: ${{ secrets.ECS_USERNAME }}
    - continue-on-error: true
      name: Test DDL Case
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 400m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./create_test_runner.sh -u ${TEST_UID} -i 2 -t ddl

          '
        username: ${{ secrets.ECS_USERNAME }}
    - continue-on-error: true
      id: ddl_reports
      name: Get DDL Test Report Files
      run: 'mkdir -p ddl

        sshpass -p ${{ secrets.ECS_PASSWORD }} scp -r -o StrictHostKeyChecking=no
        -P ${{ secrets.ECS_PORT }} ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_HOST
        }}:/root/workspace/reports/${TEST_UID}/2/surefire-reports.tar.gz ddl/surefire-reports.tar.gz

        ls -R ddl

        echo "tar file:"

        tar -zxvf ddl/surefire-reports.tar.gz -C ddl

        '
    - continue-on-error: true
      if: ${{ always() && steps.ddl_reports.outcome == 'success' }}
      name: Analyze DDL Test Result
      uses: scacap/action-surefire-report@v1
      with:
        check_name: DDL Test Result
        fail_on_test_failures: true
        report_paths: ddl/surefire-reports/TEST-*.xml
    - continue-on-error: true
      if: ${{ always() && steps.ddl_deploy.outcome == 'success' }}
      name: Clean up PolarDB-X Cluster
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 200m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./cleanup.sh -u ${TEST_UID}

          '
        username: ${{ secrets.ECS_USERNAME }}
  DML_Test:
    env:
      TEST_UID: ${{ github.run_id }}-${{ github.run_attempt }}-dml
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name,
      'ready for test')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Print ENV
      run: 'echo "test_uid: ${TEST_UID}"

        echo "git_url: ${GIT_URL}"

        echo "commit_id: ${COMMIT_ID}"

        echo "code_ref: ${CODE_REF}"

        '
    - continue-on-error: true
      id: dml_deploy
      name: Deploy PolarDB-X Cluster
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 100m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./k8s_deploy.sh -u ${TEST_UID} --repository ${GIT_URL} --ref ${CODE_REF}
          --commit ${COMMIT_ID}

          '
        username: ${{ secrets.ECS_USERNAME }}
    - continue-on-error: true
      name: Load Init Data
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 60m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./load_data_by_pod.sh -u ${TEST_UID} --parallel

          '
        username: ${{ secrets.ECS_USERNAME }}
    - continue-on-error: true
      name: Test DML Case
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 200m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./create_test_runner.sh -u ${TEST_UID} -i 1 -t dml

          '
        username: ${{ secrets.ECS_USERNAME }}
    - continue-on-error: true
      id: dml_reports
      name: Get DML Test Report Files
      run: 'mkdir -p dml

        sshpass -p ${{ secrets.ECS_PASSWORD }} scp -r -o StrictHostKeyChecking=no
        -P ${{ secrets.ECS_PORT }} ${{ secrets.ECS_USERNAME }}@${{ secrets.ECS_HOST
        }}:/root/workspace/reports/${TEST_UID}/1/surefire-reports.tar.gz dml/surefire-reports.tar.gz

        ls -R dml

        echo "tar file:"

        tar -zxvf dml/surefire-reports.tar.gz -C dml

        '
    - continue-on-error: true
      if: ${{ always() && steps.dml_reports.outcome == 'success' }}
      name: Analyze DML Test Result
      uses: scacap/action-surefire-report@v1
      with:
        check_name: DML Test Result
        fail_on_test_failures: true
        report_paths: dml/surefire-reports/TEST-*.xml
    - continue-on-error: true
      if: ${{ always() && steps.dml_deploy.outcome == 'success' }}
      name: Clean up PolarDB-X Cluster
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 200m
        envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
        host: ${{ secrets.ECS_HOST }}
        key: ${{ secrets.ECS_KEY }}
        port: ${{ secrets.ECS_PORT }}
        script: 'cd workspace/github

          ./cleanup.sh -u ${TEST_UID}

          '
        username: ${{ secrets.ECS_USERNAME }}
name: DML_DDL_Test
on:
  repository_dispatch:
    types: trigger-ga___dml_ddl_test.yaml
permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write
